apiVersion: build.openshift.io/v1
  kind: BuildConfig
    metadata:
      labels:
        app: python-sample
      name: python-sample

    spec:
      failedBuildsHistoryLimit: 3
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: 'python-sample:latest'
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        git:
          uri: 'https://github.com/snowdeer/openshift-python-sample.git'
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: 'ubuntu:latest'
            namespace: snowdeer-proj
        type: Docker    
      successfulBuildsHistoryLimit: 5 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-sample
  labels:
    app: python-sample
spec:
  template:
    metadata:
      labels:
        app: python-sample
    spec:
      containers:
      - image:  snowdeer/python-sample:latest
        name: python-sample
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: python-sample
  labels:
    app: python-sample
spec:
  ports:
  - name: python-sample
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: python-sample
  type: LoadBalancer