apiVersion: v1
kind: Deployment
metadata:
  name: python-sample
  labels:
    app: python-sample
spec:
  template:
    metadata:
      labels:
        app: python-sample
    spec:
      containers:
      - image:  snowdeer/python-sample:v1
        name: python-sample
        ports:
        - containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: python-sample
  labels:
    app: python-sample
spec:
  ports:
  - name: python-sample
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    sample-type: python-sample-pod
  type: LoadBalancer